import type { Preset } from '@/types'

const _ = 'void'
const W = 'wall'
const F = 'floor'
const D = 'door'
const w = 'water'
const T = 'tree'
const B = 'bridge'
const A = 'altar'
const t = 'treasure'
const f = 'fountain'
const g = 'grave'
const p = 'pillar'
const s = 'stairsDown'
const S = 'stairsUp'
const r = 'trap'
const c = 'cage'
const h = 'throne'
const k = 'table'

export const PRESETS: Preset[] = [
  // ── Rooms ──────────────────────────────────────────────
  {
    id: 'small-room',
    name: 'Small Room',
    description: 'A cozy 5×5 room.',
    category: 'rooms',
    grid: [
      [W,W,W,W,W],
      [W,F,F,F,W],
      [W,F,F,F,W],
      [W,F,F,F,W],
      [W,W,W,W,W],
    ],
  },
  {
    id: 'medium-room',
    name: 'Medium Room',
    description: 'A spacious 7×7 room.',
    category: 'rooms',
    grid: [
      [W,W,W,W,W,W,W],
      [W,F,F,F,F,F,W],
      [W,F,F,F,F,F,W],
      [W,F,F,F,F,F,W],
      [W,F,F,F,F,F,W],
      [W,F,F,F,F,F,W],
      [W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'large-room',
    name: 'Large Room',
    description: 'A grand 11×11 hall.',
    category: 'rooms',
    grid: [
      [W,W,W,W,W,W,W,W,W,W,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,W],
      [W,W,W,W,W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'wide-room',
    name: 'Wide Room',
    description: 'A wide 13×7 rectangular room.',
    category: 'rooms',
    grid: [
      [W,W,W,W,W,W,W,W,W,W,W,W,W],
      [W,F,F,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,F,F,F,F,W],
      [W,W,W,W,W,W,W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'cross-room',
    name: 'Cross Room',
    description: 'A cross-shaped chamber.',
    category: 'rooms',
    grid: [
      [_,_,W,W,W,W,W,_,_],
      [_,_,W,F,F,F,W,_,_],
      [_,_,W,F,F,F,W,_,_],
      [W,W,W,F,F,F,W,W,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,W,W,F,F,F,W,W,W],
      [_,_,W,F,F,F,W,_,_],
      [_,_,W,F,F,F,W,_,_],
      [_,_,W,W,W,W,W,_,_],
    ],
  },
  {
    id: 'l-room',
    name: 'L-Shape Room',
    description: 'An L-shaped room.',
    category: 'rooms',
    grid: [
      [W,W,W,W,W,W,W,W],
      [W,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,W],
      [W,F,F,F,W,W,W,W],
      [W,F,F,F,W,_,_,_],
      [W,F,F,F,W,_,_,_],
      [W,W,W,W,W,_,_,_],
    ],
  },
  {
    id: 't-room',
    name: 'T-Shape Room',
    description: 'A T-shaped meeting room.',
    category: 'rooms',
    grid: [
      [W,W,W,W,W,W,W,W,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,W,W,F,F,F,W,W,W],
      [_,_,W,F,F,F,W,_,_],
      [_,_,W,F,F,F,W,_,_],
      [_,_,W,F,F,F,W,_,_],
      [_,_,W,W,W,W,W,_,_],
    ],
  },
  {
    id: 'octagon-room',
    name: 'Octagon Room',
    description: 'An octagonal chamber.',
    category: 'rooms',
    grid: [
      [_,_,W,W,W,W,W,_,_],
      [_,W,W,F,F,F,W,W,_],
      [W,W,F,F,F,F,F,W,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,W,F,F,F,F,F,W,W],
      [_,W,W,F,F,F,W,W,_],
      [_,_,W,W,W,W,W,_,_],
    ],
  },
  {
    id: 'pillared-hall',
    name: 'Pillared Hall',
    description: 'A hall with support pillars.',
    category: 'rooms',
    grid: [
      [W,W,W,W,W,W,W,W,W],
      [W,F,F,p,F,p,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,p,F,F,F,F,F,p,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,p,F,F,F,F,F,p,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,p,F,p,F,F,W],
      [W,W,W,W,W,W,W,W,W],
    ],
  },

  // ── Corridors ─────────────────────────────────────────
  {
    id: 'corridor-h',
    name: 'Horizontal Corridor',
    description: 'A straight 1×7 horizontal passage.',
    category: 'corridors',
    grid: [
      [W,W,W,W,W,W,W,W,W],
      [F,F,F,F,F,F,F,F,F],
      [W,W,W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'corridor-v',
    name: 'Vertical Corridor',
    description: 'A straight 7×1 vertical passage.',
    category: 'corridors',
    grid: [
      [W,F,W],
      [W,F,W],
      [W,F,W],
      [W,F,W],
      [W,F,W],
      [W,F,W],
      [W,F,W],
    ],
  },
  {
    id: 'corridor-wide-h',
    name: 'Wide H-Corridor',
    description: 'A 2-tile-wide horizontal corridor.',
    category: 'corridors',
    grid: [
      [W,W,W,W,W,W,W,W,W],
      [F,F,F,F,F,F,F,F,F],
      [F,F,F,F,F,F,F,F,F],
      [W,W,W,W,W,W,W,W,W],
    ],
  },
  {
    id: 't-junction',
    name: 'T-Junction',
    description: 'A three-way corridor junction.',
    category: 'corridors',
    grid: [
      [W,F,W,_,_,_],
      [W,F,W,_,_,_],
      [F,F,F,F,F,F],
      [W,F,W,_,_,_],
      [W,F,W,_,_,_],
    ],
  },
  {
    id: 'cross-junction',
    name: 'Cross Junction',
    description: 'A four-way corridor crossing.',
    category: 'corridors',
    grid: [
      [_,_,W,F,W,_,_],
      [_,_,W,F,W,_,_],
      [F,F,F,F,F,F,F],
      [W,F,W,W,F,W,W],
      [F,F,F,F,F,F,F],
      [_,_,W,F,W,_,_],
      [_,_,W,F,W,_,_],
    ],
  },
  {
    id: 'corner',
    name: 'Corner',
    description: 'An L-shaped corridor bend.',
    category: 'corridors',
    grid: [
      [W,F,W,W,W],
      [W,F,F,F,W],
      [W,W,W,F,W],
      [_,_,_,F,W],
    ],
  },
  {
    id: 's-corridor',
    name: 'S-Corridor',
    description: 'A snaking S-shaped passage.',
    category: 'corridors',
    grid: [
      [F,F,F,W,W],
      [W,W,F,F,F],
      [W,W,W,W,F],
      [F,F,F,F,F],
      [W,F,W,W,W],
      [W,F,F,F,W],
      [W,W,W,F,F],
    ],
  },

  // ── Features ──────────────────────────────────────────
  {
    id: 'vault',
    name: 'Treasure Vault',
    description: 'A small heavily-walled treasure room.',
    category: 'features',
    grid: [
      [W,W,W,W,W],
      [W,F,F,F,W],
      [W,F,t,F,W],
      [W,F,F,F,W],
      [W,W,W,W,W],
    ],
  },
  {
    id: 'fountain-hall',
    name: 'Fountain Hall',
    description: 'A room with a central fountain.',
    category: 'features',
    grid: [
      [W,W,W,W,W,W,W],
      [W,F,F,F,F,F,W],
      [W,F,F,f,F,F,W],
      [W,F,f,f,f,F,W],
      [W,F,F,f,F,F,W],
      [W,F,F,F,F,F,W],
      [W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'lake',
    name: 'Lake',
    description: 'A small body of water.',
    category: 'features',
    grid: [
      [_,_,w,w,w,_,_],
      [_,w,w,w,w,w,_],
      [w,w,w,w,w,w,w],
      [w,w,w,w,w,w,w],
      [w,w,w,w,w,w,w],
      [_,w,w,w,w,w,_],
      [_,_,w,w,w,_,_],
    ],
  },
  {
    id: 'forest',
    name: 'Forest Grove',
    description: 'A cluster of trees.',
    category: 'features',
    grid: [
      [T,_,T,_,T,_],
      [_,T,_,T,_,T],
      [T,_,T,_,T,_],
      [_,T,_,T,_,T],
      [T,_,T,_,T,_],
    ],
  },
  {
    id: 'graveyard',
    name: 'Graveyard',
    description: 'A burial ground with graves.',
    category: 'features',
    grid: [
      [W,W,W,W,W,W,W],
      [W,g,F,g,F,g,W],
      [W,F,F,F,F,F,W],
      [W,g,F,g,F,g,W],
      [W,F,F,F,F,F,W],
      [W,g,F,g,F,g,W],
      [W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'altar-room',
    name: 'Altar Room',
    description: 'A somber chamber with an altar.',
    category: 'features',
    grid: [
      [W,W,W,W,W],
      [W,F,F,F,W],
      [W,F,A,F,W],
      [W,F,F,F,W],
      [W,W,W,W,W],
    ],
  },

  // ── Dungeon ───────────────────────────────────────────
  {
    id: 'entrance-hall',
    name: 'Entrance Hall',
    description: 'A grand entrance with stairs down.',
    category: 'dungeon',
    grid: [
      [W,W,W,W,W,W,W],
      [D,F,F,F,F,F,D],
      [W,F,F,F,F,F,W],
      [W,F,F,s,F,F,W],
      [W,F,F,F,F,F,W],
      [D,F,F,F,F,F,D],
      [W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'prison',
    name: 'Prison',
    description: 'A cell block.',
    category: 'dungeon',
    grid: [
      [W,W,W,W,W,W,W,W,W],
      [D,F,F,F,W,F,F,F,D],
      [W,c,F,c,W,F,F,F,W],
      [W,F,F,F,W,W,W,W,W],
      [W,F,F,F,W,F,F,F,W],
      [W,c,F,c,W,F,F,F,W],
      [W,F,F,F,W,F,F,F,W],
      [W,W,W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'bridge',
    name: 'Bridge',
    description: 'A bridge crossing water.',
    category: 'dungeon',
    grid: [
      [W,F,W],
      [w,B,w],
      [w,B,w],
      [w,B,w],
      [w,B,w],
      [w,B,w],
      [W,F,W],
    ],
  },
  {
    id: 'shop',
    name: 'Shop',
    description: 'A merchant shop.',
    category: 'dungeon',
    grid: [
      [W,W,W,W,W,W,W],
      [D,F,F,F,F,F,D],
      [W,k,k,F,k,k,W],
      [W,F,F,F,F,F,W],
      [W,k,k,F,k,k,W],
      [W,F,F,F,F,F,W],
      [W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    description: 'A kitchen with tables.',
    category: 'dungeon',
    grid: [
      [W,W,W,W,W,W,W],
      [W,F,F,F,F,F,W],
      [W,k,k,F,k,k,W],
      [W,F,F,F,F,F,W],
      [W,k,k,F,k,k,W],
      [W,F,F,F,F,F,W],
      [W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'throne-room',
    name: 'Throne Room',
    description: 'A royal throne chamber.',
    category: 'dungeon',
    grid: [
      [W,W,W,W,W,W,W,W,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,h,h,F,F,F,W],
      [W,F,F,h,h,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,F,F,F,F,F,F,F,W],
      [W,W,W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'stairs-set',
    name: 'Stairs Set',
    description: 'Up and down stairs side by side.',
    category: 'dungeon',
    grid: [
      [W,W,W,W,W],
      [W,F,F,F,W],
      [W,S,F,s,W],
      [W,F,F,F,W],
      [W,W,W,W,W],
    ],
  },

  // ── Traps ─────────────────────────────────────────────
  {
    id: 'trap-corridor',
    name: 'Trapped Corridor',
    description: 'A corridor lined with traps.',
    category: 'traps',
    grid: [
      [W,W,W,W,W,W,W,W,W],
      [r,F,F,r,F,F,r,F,r],
      [W,W,W,W,W,W,W,W,W],
    ],
  },
  {
    id: 'trap-room',
    name: 'Trap Room',
    description: 'A room with a trapped floor.',
    category: 'traps',
    grid: [
      [W,W,W,W,W,W,W],
      [W,r,F,r,F,r,W],
      [W,F,F,F,F,F,W],
      [W,r,F,r,F,r,W],
      [W,F,F,F,F,F,W],
      [W,r,F,r,F,r,W],
      [W,W,W,W,W,W,W],
    ],
  },
]

export const PRESET_CATEGORIES: { key: Preset['category']; label: string }[] = [
  { key: 'rooms', label: 'Rooms' },
  { key: 'corridors', label: 'Corridors' },
  { key: 'features', label: 'Features' },
  { key: 'dungeon', label: 'Dungeon' },
  { key: 'traps', label: 'Traps' },
]
